name: Runner CI

on:
  push:
    branches:
      - master
    paths:
      - runner/**/*

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Clone
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2-beta
        with:
          node-version: '12'

      - name: Build
        run: |
          cd runner
          yarn install
          yarn pack

      - name: Upload Binaries
        uses: actions/upload-artifact@v2
        width:
          name: Binary files
          path: runner/dist/*
          if-no-files-found: error
