name: Web CD

on:
  push:
    branches:
      - master
    paths:
      - web/**/*

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Clone
        uses: actions@checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2-beta
        with:
          node-version: '12'

      - name: Build
        run: |
          cd web
          yarn install
          yarn build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: web/build
          CLEAN: true
